apiVersion: v1
kind: Pod
metadata:
  name: broken-pod-too-much-mem
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sleep
        - "3600"
      resources:
        requests:
          memory: 100Gi
